[tools]
# general
chezmoi = "latest"
bun = "latest"     # for `npm:` install
uv = "latest"      # for `pipx:` install
aqua = "latest"

# programming
gh = "latest"
ghq = "latest"

# shell
"aqua:nushell/nushell" = "latest"
starship = "latest"

# tools
rg = "latest"
fzf = "latest"
fd = "latest"
yazi = "latest"
bottom = "latest"
duf = "latest"

# ai
gemini = "latest"
opencode = "latest"
"aqua:github/copilot-cli" = "0.0.373"
"aqua:github/github-mcp-server" = "0.26.3"
"npm:@upstash/context7-mcp" = "latest"
"pipx:git+https://github.com/oraios/serena.git" = "latest"

[env]
EDITOR = "nvim"

[settings]
npm.package_manager = "bun"
pipx.uvx = true
aqua.baked_registry = false
