[tools]
chezmoi = "latest"
gh = "latest"
neovim = "latest"
"aqua:nushell/nushell" = "latest"
zellij = "latest"
starship = "latest"
lazygit = "latest"
tree-sitter = "latest"
rg = "latest"
fzf = "latest"
fd = "latest"
node = "latest"
yazi = "latest"

[env]
EDITOR = "nvim"

